### ISSUE TITLE
Markdown 语法生成错误

### ISSUE THREAD

**Issue by Wsine** [chyroc/lark_docs_md#5]
hello，我最近基于这个解析库开发了一个小工具 [feishu2md](https://github.com/Wsine/feishu2md)，在实际使用中发现了一个问题。

当解析文本中有连续的两个 Block 为 Paragraph 的时候，解析的文本为

```markdown
这是段落一。
这是段落二。
```

很多的 markdown 编辑器都无法将其渲染为两个段落。而且这也不符合 CommonMark 的标准 ([ref](https://daringfireball.net/projects/markdown/syntax#p))。

同样地，如果 Paragraph 紧接的是一个 List Paragraph，那么它的缩进就会出问题。

 我简单尝试了一下，一个最简单的方法可能是将下面的 47 行代码改为 `buf.WriteString("\n\n")`，暂时没看到对其它元素的渲染影响。不知道还有没有其它更好的改法，因此提出来探讨一下。

https://github.com/chyroc/lark_docs_md/blob/76c988357d4f7f5217a05fe6fa04b30f52e60de4/md.go#L42-L51

**Comment by chyroc** [comment]
go get github.com/chyroc/lark_docs_md@93abd32
